import type { Metadata } from "next";
import "./globals.css";
import ProviderGlobal from "../redux/provider";
import Navbar from "../components/nav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className="antialiased"
      >
        <ProviderGlobal>
          <div className="flex flex-col h-screen bg-notion-background">
            {children}
            <Navbar />
          </div>
        </ProviderGlobal>
      </body>
    </html>
  );
}
